### ISSUE TITLE
the readme example is not working

### ISSUE THREAD

**Issue by SamuelAllain** [galette-community/docker#6]
Hi, it's me again. I wanted to warn you that the readme example is not functional. There is no galette/galette:**latest**. And this command has a flaw :

docker run  -d -p 8080:80 --name galette
-v  /path/to/config.inc.php:/var/www/galette/config/config.inc.php \
-v  /path/to/data/attachments:/var/www/galette/data/attachments \
-v  /path/to/data/cache:/var/www/galette/data/cache \
-v  /path/to/data/files:/var/www/galette/data/files \
-v  /path/to/data/logs:/var/www/galette/data/logs \
-v  /path/to/data/photos:/var/www/galette/data/photos \
**- ./data/templates_c:/var/www/galette/data/templates_c \
galette/galette:latest**

It'd be nice to explain what has to be copied from the first container and how (`docker cp` ?).
Thank you !

**Comment by Hiobi** [comment]
Hi !
The Readme and docs files need to be update with more details, since the docker image has been rewrite / update 4 months ago. 
latest tag was removed 4 months ago, to avoid issue / misunderstood since plugin maps seems not working with galette 0.9.6 under galette. 

Galette docker still under development but not very active, I'm currently alone on this project (new job, new home), I will take a look next days. Help is welcome. :)

I use docker-compose to launch Galette, currently under v0.9.6 (dev-master) for my community (https://adhesion.nefald.fr/), here an example : 

```

version: '3.7'
services:
  galette:
    image: galette/galette:dev-master
    container_name: galette
    stdin_open: true
    tty: true
    ports:
      - 8080:80
    environment:
      - TZ=Europe/Paris
      - RM_INSTALL_FOLDER=0
    volumes:
      - /docker/galette/data/attachments:/var/www/galette/data/attachments
      - /docker/galette/data/cache:/var/www/galette/data/cache
#      - /docker/galette/data/exports:/var/www/galette/data/exports
      - /docker/galette/data/files:/var/www/galette/data/files
#      - /docker/galette/data/logs:/var/www/galette/data/logs
      - /docker/galette/data/photos:/var/www/galette/data/photos
#      - /docker/galette/data/tempimages:/var/www/galette/data/tempimages
#      - /docker/galette/data/template_c:/var/www/galette/data/template_c
      - /docker/galette/data/templates_c:/var/www/galette/data/templates_c
      - /docker/galette/config/config.inc.php:/var/www/galette/config/config.inc.php
      - /docker/galette/config/behavior.inc.php:/var/www/galette/config/behavior.inc.php
      - /docker/galette/galette_local.css:/var/www/galette/webroot/themes/default/galette_local.css

```

Thanks !

**Comment by SamuelAllain** [comment]
Hi and thanks for that work and your reply ! I'll try to make that work again. In case of success, I will make a PR for longer explanations :)

**Comment by SamuelAllain** [comment]
Hi @Hiobi, I spent some hours on this but could not make it work. I used docker compose to have a PostgreSQL container (which works because I can connect with pgAdmin in another container) but it seems galette cannot connect. It returns a blank page after the database step with no explanation, it is difficult to debug. So for now, I cannot help you update the README, sorry. Maybe I'll try once to go with nginx instead of Apache cause I did it once to try [Garradin](https://github.com/SamuelAllain/docker-garradin)

**Comment by Hiobi** [comment]
Hi @SamuelAllain, thansk for your reply !

- I've just push two images with tags : update `0.9.6` and re-add `latest`. Plugin Maps is disabled for the moment. You should try it. galette/galette:latest :)
- You should switch the environment variable "RM_INSTALL_FOLDER" to "0" for the first install, then turn it to "1" when you have already install Galette. This variable remove the install folder at container launch, for security purpose. 
https://doc.galette.eu/fr/master/installation/galette.html#installation-end
- I will check about PostgreSQL, the PHP mod is enabled by default. My image is based on [PHP:8.0-apache image](https://hub.docker.com/layers/php/library/php/8.0-apache/images/sha256-9394291bd7b1bf1c03ee43e613107fe1563582ac853f441ce8a7abf2a4128502?context=explore), which is base on Debian Buster. Maybe it's already include.

**Comment by SamuelAllain** [comment]
Thank you for improving all that. I think that it could be useful in the future to explain in the README that you need a database engine to make it work. Ideally it could be included in a second container so that you don't have to install anything on your computer. Something like that (for a first run with no volume)

```
version: '3.7'

services:
  db:
    image: postgres
    restart: always
    hostname: 'galette-postgres'  # AND HERE 
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=galette
      - POSTGRES_USER=postgres # superuser definition
      - POSTGRES_PASSWORD=galette123 

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # to use when connecting to localhost:5050
      PGADMIN_DEFAULT_PASSWORD: root # to use when connecting to localhost:5050
    ports:
      - "5050:80"
    depends_on:
      - db

  galette:
     image: galette/galette:latest
     container_name: ga
     stdin_open: true
     tty: true
     environment:
       - TZ=Europe/Paris # Define Timezone. Europe/Paris by default.
       - RM_INSTALL_FOLDER=0 # 0 by default. Turn to "1" to remove "install" folder (for security purpose), after installation/update.    
     ports:
       - 8080:80
     depends_on:
       - db

```
Unfortunately I still cannot make it work. Eventually I will stick to the software Garradin. Thank you !
